### PR TITLE
Make man page generation optional.

### PR DESCRIPTION
**Pull request by Scheirle**
Refs:
#83

### CODE REVIEW

**Comment by florianjacob** [comment]
:shipit:

**Comment by florianjacob** [comment]
Still needed:

 * [ ] if man is included in make all, it's not needed to run separately in travis anymore
 * [ ] override zipped man pages with `zip -f`
 * [ ] add_custom_target is *always* rebuilt, bernhard is unhappy

**Comment by Scheirle** [comment]
Fixed the always rebuilt issue by setting correct working directories and using cmakes own zip function.

**Comment by florianjacob** [comment]
cmake zip works with Debian stable, cool! :+1:

**Pull request merged**
