### PR TITLE
include std::array to fix building error

### PR DESCRIPTION
**Pull request by a-andreyev**
without this I'm not able to build master branch. With this include it's building and working

### CODE REVIEW

**Comment by SrTobi** [comment]
I get the same error. The question is why are we not using `std::array` (then `<array>` has to be included). I did a quick compile and it compiles with `boost::asio`. Tests are passing as well... do we even have tests for the server? 😃

**Comment by florianjacob** [comment]
@Scheirle as `boost::array` is only used in `http_request.hpp`, I'm assigning you. Do you have any objections on it being replaced with an `std::array`?

@a-andreyev thanks for your contribution & interest. 😄 👍 Do you want to extend it a little and replace `boost::array` with `std::array`?

**Comment by a-andreyev** [comment]
moved from boost to std array, building and running too, thanks for the hint @SrTobi

**Comment by Scheirle** [comment]
Thanks @a-andreyev. Apologies for the delay!

**Pull request merged**
