### PR TITLE
Fix windows build, unit tests and operation

### PR DESCRIPTION
**Pull request by florianjacob**
Should make #75 possible as soon as finished.

### CODE REVIEW

**Comment by Scheirle** [comment]
`vcpkg install cairo freetype` is exceeding the appveyor time limit (>60min).
Other have the same issue: https://github.com/behdad/harfbuzz/pull/422

**Comment by florianjacob** [comment]
Whoever of us gets his hands on a Windows installation first: Please install [vcpkg](https://github.com/Microsoft/vcpkg) and try to install freetype to see whether this is an appveyor or a vcpkg issue.

**Comment by florianjacob** [comment]
With https://github.com/appveyor/ci/issues/1076 now being resolved, this might actually just work!

**Comment by florianjacob** [comment]
finally works!

**Pull request merged**
