### PR TITLE
simplify CMake code

### PR DESCRIPTION
**Pull request by DerDakon**

### CODE REVIEW

**Comment by DerDakon** [comment]
I had to remove the last commit, older CMake versions failed in finding things like threads if the C compiler is not enabled.

**Comment by DerDakon** [comment]
ping?

**Comment by florianjacob** [comment]
Assigning to our CMake expert @Scheirle as he is probably the only one of the team who can understand what you were changing here. :wink:

**Comment by florianjacob** [comment]
@DerDakon note that time goes slower in the alacarte universe, I mean we're trying to release the next version for 2 years now… :laughing:

@SrTobi Bitte warten… der nächste freie Reviewer schaut sich dein #108 an. :laughing:

**Pull request merged**
