### PR TITLE
Fix Build (#79)

### LINKED ISSUE #79: Build error
```
In file included from /usr/include/boost/test/tools/floating_point_comparison.hpp:21:0,
                 from /usr/include/boost/test/tools/old/impl.hpp:21,
                 from /usr/include/boost/test/test_tools.hpp:46,
                 from /usr/include/boost/test/unit_test.hpp:18,
                 from /tmp/16.23.21/alacarte/tests/parser/grammar-tests/../../tests.hpp:15,
                 from /tmp/16.23.21/alacarte/tests/parser/grammar-tests/color_grammar_test.cpp:2:
/usr/include/boost/test/tools/detail/print_helper.hpp: In instantiation of ‘struct boost::test_tools::tt_detail::print_log_value<Color>’:
/usr/include/boost/test/tools/detail/print_helper.hpp:178:5:   required from ‘std::ostream& boost::test_tools::tt_detail::operator<<(std::ostream&, const boost::test_tools::tt_detail::print_helper_t<T>&) [with T = Color; std::ostream = std::basic_ostream<char>]’
/usr/include/boost/test/utils/lazy_ostream.hpp:66:29:   required from ‘std::ostream& boost::unit_test::lazy_ostream_impl<PrevType, T, StorageT>::operator()(std::ostream&) const [with PrevType = boost::unit_test::lazy_ostream; T = boost::test_tools::tt_detail::print_helper_t<Color>; StorageT = const boost::test_tools::tt_detail::print_helper_t<Color>&; std::ostream = std::basic_ostream<char>]’
/tmp/16.23.21/alacarte/tests/parser/grammar-tests/color_grammar_test.cpp:59:24:   required from here
/usr/include/boost/test/tools/detail/print_helper.hpp:47:5: error: ‘value’ is not a member of ‘boost::has_left_shift<std::basic_ostream<char>, Color, boost::detail::has_left_shift_impl::dont_care>’
     BOOST_STATIC_ASSERT_MSG( (boost::has_left_shift<std::ostream,T>::value),
     ^
make[2]: *** [CMakeFiles/unitTests_parser.dir/build.make:63: CMakeFiles/unitTests_parser.dir/tests/parser/grammar-tests/color_grammar_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1315: CMakeFiles/unitTests_parser.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

### PR DESCRIPTION
**Pull request by Scheirle**
Fixes #79.

### CODE REVIEW

**Comment by florianjacob** [comment]
Sorry for the inconvenience to have merged your PRs in the wrong order. :frowning:

**Comment by florianjacob** [comment]
Tried to solve rebase conflicts…

**Comment by florianjacob** [comment]
Big :+1: for the use of `= default;` instead of `() { }`, I actually didn't know / forgot that syntax existed. 

The only thing I see left to do is to convert the remaining other constructors / destructors to that syntax to be consistently explicit (or delete them at your choice). A quick `rg "\(\) \{\s*\}"` turned up these candidates:

* `~NonPrerenderingRequestManager() {}
* `MockSelector() {}`
* `MockGeodata() : Geodata() {}`
* `~PNGRenderCanvas() {}`
* `~RenderCanvas() {}`
*  `RenderAttributes() {}`

**Comment by Scheirle** [comment]
> The only thing I see left to do is to convert the remaining other constructors / destructors to that syntax to be consistently explicit.

Done

**Comment by florianjacob** [comment]
Magnificent! :+1: for additional whitespace cleanup.

:shipit:

**Pull request merged**
